/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查，Electron 主进程据此判断后端是否就绪。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect */
        post: operations["detect_api_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purify/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Purify Status
         * @description 潜空间净化能力状态：依赖、权重缓存、策略与推理设备。
         */
        get: operations["purify_status_api_purify_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purify/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purify Install
         * @description 一键准备净化权重（10MB 级 TAESD）；立即返回，前端轮询状态直到 ready。
         */
        post: operations["purify_install_api_purify_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collusion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Collusion
         * @description 共谋平均：同一内容的多份不同水印副本对齐后平均（研究/授权测试）。
         */
        post: operations["collusion_api_collusion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/similarity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Similarity */
        post: operations["similarity_api_similarity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Scan */
        post: operations["import_scan_api_import_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Library */
        get: operations["demo_library_api_demo_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Frame
         * @description 抽取视频指定时间点的帧（PNG），供预览与前后对比渲染。
         */
        get: operations["frame_api_frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thumb
         * @description 返回等比缩放的首帧缩略图（JPEG），带磁盘缓存，供素材封面使用。
         */
        get: operations["thumb_api_thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library List
         * @description 返回持久化素材库（最新导入在前），并标记内容完全相同的重复副本。
         */
        get: operations["library_list_api_library_get"];
        put?: never;
        /**
         * Library Add
         * @description 登记一个本地视频到素材库；内容完全相同的文件不重复导入。
         */
        post: operations["library_add_api_library_post"];
        /**
         * Library Remove
         * @description 从素材库移除记录与对应产物；源视频文件一律保留，由用户手动管理。
         */
        delete: operations["library_remove_api_library_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Library Clear
         * @description 清空素材库：移除全部素材记录并删除对应产物文件与记录。
         *
         *     源视频文件一律保留（无论位于何处），由用户手动管理。
         */
        delete: operations["library_clear_api_library_all_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Media
         * @description 流式返回视频文件，支持 HTTP Range，播放器可随时拖动定位。
         */
        get: operations["media_api_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Video
         * @description 接收网页端导入的视频：流式落盘，去重与入库交给服务层。
         */
        post: operations["import_video_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audio/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audio Analyze
         * @description 音频分析：波形、对数频谱与回声隐藏置信度。
         */
        post: operations["audio_analyze_api_audio_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/desensitize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desensitize */
        post: operations["desensitize_api_desensitize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Videos
         * @description 把已处理素材的产物复制到设置中的导出目录。
         */
        post: operations["export_videos_api_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Outputs
         * @description 列出源素材的全部处理产物（清洗/修复/候选），最新在前。
         */
        get: operations["outputs_api_outputs_get"];
        put?: never;
        post?: never;
        /**
         * Delete Output
         * @description 删除指定处理产物（仅限清洗/修复/候选命名）。
         */
        delete: operations["delete_output_api_outputs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outputs/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Outputs Counts
         * @description 素材库各源素材的产物数量汇总。
         */
        get: operations["outputs_counts_api_outputs_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Products List
         * @description 全部处理产物的全局清单，用于产物管理页查看占用与清理。
         */
        get: operations["products_list_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Products Delete
         * @description 批量删除产物文件与记录；仅允许清洗/修复/候选命名，绝不触碰源视频。
         */
        post: operations["products_delete_api_products_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ffmpeg/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Ffmpeg
         * @description 用户手动指定本机已有的 ffmpeg 可执行文件。
         */
        post: operations["select_ffmpeg_api_ffmpeg_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ffmpeg/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ffmpeg Install Status
         * @description 查询视频处理引擎一键安装进度。
         */
        get: operations["ffmpeg_install_status_api_ffmpeg_install_get"];
        put?: never;
        /**
         * Install Ffmpeg
         * @description 后台下载静态视频处理引擎，前端轮询状态直到完成。
         */
        post: operations["install_ffmpeg_api_ffmpeg_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        /** Remove Jobs */
        delete: operations["remove_jobs_api_jobs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Job */
        post: operations["pause_job_api_jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resume_job_api_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Job Priority */
        post: operations["set_job_priority_api_jobs__job_id__priority_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Templates */
        get: operations["get_templates_api_templates_get"];
        put?: never;
        /** Post Template */
        post: operations["post_template_api_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Template */
        put: operations["put_template_api_templates__template_id__put"];
        post?: never;
        /** Remove Template */
        delete: operations["remove_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Variants
         * @description 产物记录清单：按源文件过滤，返回完整参数与指标快照。
         */
        get: operations["list_variants_api_variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_video_api_import_post */
        Body_import_video_api_import_post: {
            /** File */
            file: string;
        };
        /**
         * CollusionRequest
         * @description 共谋平均请求：同一内容的多份不同水印副本。
         */
        CollusionRequest: {
            /** Paths */
            paths: string[];
            /** Output */
            output: string;
            /**
             * Mode
             * @default mean
             * @enum {string}
             */
            mode: "mean" | "median";
            /**
             * Max Frames
             * @default 600
             */
            max_frames: number;
        };
        /**
         * DesensitizeRequest
         * @description 直接调用 /api/desensitize 的请求体：在选项集之上补充路径。
         */
        DesensitizeRequest: {
            /**
             * Reorder
             * @default false
             */
            reorder: boolean;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Recrop
             * @default 0
             */
            recrop: number;
            /**
             * Regrade
             * @default true
             */
            regrade: boolean;
            /**
             * Perturb
             * @default 0
             */
            perturb: number;
            /**
             * Audio Remix
             * @default true
             */
            audio_remix: boolean;
            /**
             * Sharpness
             * @default true
             */
            sharpness: boolean;
            /**
             * Color Restore
             * @default true
             */
            color_restore: boolean;
            /**
             * Denoise
             * @default false
             */
            denoise: boolean;
            /**
             * Anti Reembed
             * @default false
             */
            anti_reembed: boolean;
            /**
             * Banner
             * @default
             */
            banner: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Codec
             * @default libx264
             */
            codec: string;
            /**
             * Lossless
             * @default false
             */
            lossless: boolean;
            /**
             * Preset
             * @default veryfast
             */
            preset: string;
            /**
             * Spoof
             * @default false
             */
            spoof: boolean;
            /** Bitrate Kbps */
            bitrate_kbps?: number | null;
            /** Gop */
            gop?: number | null;
            /** Resolution */
            resolution?: string | null;
            /** Fps Out */
            fps_out?: number | null;
            /**
             * Hardware
             * @default false
             */
            hardware: boolean;
            /** Transform Strategy */
            transform_strategy?: string | null;
            /**
             * Phash Attack
             * @default false
             */
            phash_attack: boolean;
            /**
             * Phash Epsilon
             * @default 0.03
             */
            phash_epsilon: number;
            /**
             * Phash Iters
             * @default 40
             */
            phash_iters: number;
            /**
             * Multi Hash Attack
             * @default false
             */
            multi_hash_attack: boolean;
            /**
             * Dhash Attack
             * @default false
             */
            dhash_attack: boolean;
            /**
             * Shot Retime
             * @default false
             */
            shot_retime: boolean;
            /**
             * Shot Retime Min
             * @default 0.98
             */
            shot_retime_min: number;
            /**
             * Shot Retime Max
             * @default 1.04
             */
            shot_retime_max: number;
            /**
             * Cut Jitter
             * @default 0
             */
            cut_jitter: number;
            /**
             * Audio Strong
             * @default false
             */
            audio_strong: boolean;
            /**
             * Echo Defeat
             * @default false
             */
            echo_defeat: boolean;
            /**
             * Skip Vmaf
             * @default false
             */
            skip_vmaf: boolean;
            /**
             * Filter Scale
             * @default 0
             */
            filter_scale: number;
            /**
             * Rotate
             * @default 0
             */
            rotate: number;
            /**
             * Median
             * @default 0
             */
            median: number;
            /**
             * Noise
             * @default 0
             */
            noise: number;
            /**
             * Requant
             * @default 0
             */
            requant: number;
            /**
             * Dct Step
             * @default 0
             */
            dct_step: number;
            /**
             * Drop Every
             * @default 0
             */
            drop_every: number;
            /**
             * Temporal Sub
             * @default 0
             */
            temporal_sub: number;
            /**
             * Fft Phase
             * @default 0
             */
            fft_phase: number;
            /**
             * Dwt Detail
             * @default 0
             */
            dwt_detail: number;
            /**
             * Hsv Jitter
             * @default 0
             */
            hsv_jitter: number;
            /**
             * Face Perturb
             * @default 0
             */
            face_perturb: number;
            /**
             * Lpc Attack
             * @default 0
             */
            lpc_attack: number;
            /**
             * Copy Attack
             * @default 0
             */
            copy_attack: number;
            /**
             * Native Temporal
             * @default false
             */
            native_temporal: boolean;
            /**
             * Quality Protect
             * @default false
             */
            quality_protect: boolean;
            /**
             * Psnr Target
             * @default 38
             */
            psnr_target: number;
            /**
             * Ssim Target
             * @default 0.94
             */
            ssim_target: number;
            /**
             * Jitter
             * @default 0
             */
            jitter: number;
            /**
             * Perspective
             * @default 0
             */
            perspective: number;
            /**
             * Warp
             * @default 0
             */
            warp: number;
            /**
             * Subtract Beta
             * @default 0
             */
            subtract_beta: number;
            /**
             * Saliency
             * @default 0
             */
            saliency: number;
            /**
             * Chroma Levels
             * @default 0
             */
            chroma_levels: number;
            /**
             * Native Filters
             * @default false
             */
            native_filters: boolean;
            /**
             * Purify Strength
             * @default 0
             */
            purify_strength: number;
            /**
             * Purify Detail
             * @default 1
             */
            purify_detail: number;
            /**
             * Purify Detail Sigma
             * @default 0
             */
            purify_detail_sigma: number;
            /**
             * Purify Detail Wide
             * @default false
             */
            purify_detail_wide: boolean;
            /**
             * Known Scheme
             * @default
             * @enum {string}
             */
            known_scheme: "" | "luma" | "chroma" | "videoseal" | "pixelseal" | "wam" | "trustmark" | "mbrs";
            /**
             * Purify Temporal
             * @default 0
             */
            purify_temporal: number;
            /**
             * Purify Max Edge
             * @default 256
             */
            purify_max_edge: number;
            /**
             * Purify Batch
             * @default 8
             */
            purify_batch: number;
            /**
             * Embedding Attack
             * @default
             * @enum {string}
             */
            embedding_attack: "" | "auto" | "luma" | "chroma" | "both";
            /**
             * Embedding Strength
             * @default 0
             */
            embedding_strength: number;
            /**
             * Embedding Variant
             * @default v2
             * @enum {string}
             */
            embedding_variant: "legacy" | "v2";
            /**
             * Embedding Aggressive
             * @default false
             */
            embedding_aggressive: boolean;
            /**
             * Auto Profile
             * @default false
             */
            auto_profile: boolean;
            /** Path */
            path: string;
            /** Output */
            output: string;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Paths */
            paths: string[];
            /** Export Dir */
            export_dir?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRequest */
        JobRequest: {
            /** Name */
            name: string;
            /** Parallelism */
            parallelism?: number | null;
            /** Tasks */
            tasks: components["schemas"]["TaskSpec"][];
        };
        /** PairRequest */
        PairRequest: {
            /** A */
            a: string;
            /** B */
            b: string;
        };
        /** PathRequest */
        PathRequest: {
            /** Path */
            path: string;
        };
        /** PriorityRequest */
        PriorityRequest: {
            /**
             * Priority
             * @default 0
             */
            priority: number;
        };
        /** ProductsRequest */
        ProductsRequest: {
            /** Paths */
            paths: string[];
        };
        /** ScanRequest */
        ScanRequest: {
            /** Path */
            path: string;
        };
        /** TaskSpec */
        TaskSpec: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "detect" | "desensitize";
            /** Path */
            path: string;
            /**
             * Options
             * @default {}
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** TemplateCreate */
        TemplateCreate: {
            /** Name */
            name: string;
            payload: components["schemas"]["TemplatePayload"];
        };
        /**
         * TemplatePayload
         * @description 模板持久化 payload：camelCase 是 UI/DB 既有线格式。
         *
         *     extra=ignore 容忍旧版本迁移遗留字段（level/restruct/perturb/audio 等），
         *     只约束与校验当前面板真实使用的字段。
         */
        TemplatePayload: {
            /**
             * Audioremix
             * @default false
             */
            audioRemix: boolean;
            /**
             * Echodefeat
             * @default false
             */
            echoDefeat: boolean;
            /**
             * Antireembed
             * @default false
             */
            antiReembed: boolean;
            /**
             * Rotate
             * @default 0
             */
            rotate: number;
            /**
             * Hashattack
             * @default false
             */
            hashAttack: boolean;
            /**
             * Hashepsilon
             * @default 0.045
             */
            hashEpsilon: number;
            /**
             * Hashmode
             * @default joint
             */
            hashMode: string;
            /**
             * Requant
             * @default 0
             */
            requant: number;
            /**
             * Noise
             * @default 0
             */
            noise: number;
            /**
             * Dctstep
             * @default 0
             */
            dctStep: number;
            /**
             * Audiostrong
             * @default false
             */
            audioStrong: boolean;
            /**
             * Regradeon
             * @default false
             */
            regradeOn: boolean;
            /**
             * Recropon
             * @default false
             */
            recropOn: boolean;
            /**
             * Temporalsub
             * @default 0
             */
            temporalSub: number;
            /**
             * Fftphase
             * @default 0
             */
            fftPhase: number;
            /**
             * Dwtdetail
             * @default 0
             */
            dwtDetail: number;
            /**
             * Hsvjitter
             * @default 0
             */
            hsvJitter: number;
            /**
             * Jitter
             * @default 0
             */
            jitter: number;
            /**
             * Perspective
             * @default 0
             */
            perspective: number;
            /**
             * Warp
             * @default 0
             */
            warp: number;
            /**
             * Faceperturb
             * @default 0
             */
            facePerturb: number;
            /**
             * Lpcattack
             * @default 0
             */
            lpcAttack: number;
            /**
             * Copyattack
             * @default 0
             */
            copyAttack: number;
            /**
             * Nativetemporal
             * @default false
             */
            nativeTemporal: boolean;
            /**
             * Qualityprotect
             * @default false
             */
            qualityProtect: boolean;
            /**
             * Psnrtarget
             * @default 38
             */
            psnrTarget: number;
            /**
             * Ssimtarget
             * @default 0.94
             */
            ssimTarget: number;
            /**
             * Purifystrength
             * @default 0
             */
            purifyStrength: number;
            /**
             * Purifydetail
             * @default 1
             */
            purifyDetail: number;
            /**
             * Purifydetailsigma
             * @default 0
             */
            purifyDetailSigma: number;
            /**
             * Purifydetailwide
             * @default false
             */
            purifyDetailWide: boolean;
            /**
             * Knownscheme
             * @default
             * @enum {string}
             */
            knownScheme: "" | "luma" | "chroma" | "videoseal" | "pixelseal" | "wam" | "trustmark" | "mbrs";
            /**
             * Purifytemporal
             * @default 0
             */
            purifyTemporal: number;
            /**
             * Purifymaxedge
             * @default 256
             */
            purifyMaxEdge: number;
            /**
             * Purifybatch
             * @default 8
             */
            purifyBatch: number;
            /**
             * Embeddingattack
             * @default
             * @enum {string}
             */
            embeddingAttack: "" | "auto" | "luma" | "chroma" | "both";
            /**
             * Embeddingstrength
             * @default 0
             */
            embeddingStrength: number;
            /**
             * Embeddingvariant
             * @default v2
             * @enum {string}
             */
            embeddingVariant: "legacy" | "v2";
            /**
             * Embeddingaggressive
             * @default false
             */
            embeddingAggressive: boolean;
            /**
             * Autoprofile
             * @default false
             */
            autoProfile: boolean;
            /**
             * Sharpness
             * @default false
             */
            sharpness: boolean;
            /**
             * Colorrestore
             * @default false
             */
            colorRestore: boolean;
            /**
             * Denoise
             * @default false
             */
            denoise: boolean;
            /**
             * Spoof
             * @default false
             */
            spoof: boolean;
            /**
             * Codec
             * @default H.264
             * @enum {string}
             */
            codec: "H.264" | "H.265";
            /**
             * Lossless
             * @default false
             */
            lossless: boolean;
            /**
             * Resolution
             * @default 保持原始分辨率
             */
            resolution: string;
            /** Bitrate */
            bitrate?: number | null;
            /** Gop */
            gop?: number | null;
            /** Fpsout */
            fpsOut?: number | null;
        };
        /** TemplateUpdate */
        TemplateUpdate: {
            /** Name */
            name: string;
            payload: components["schemas"]["TemplatePayload"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    detect_api_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purify_status_api_purify_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    purify_install_api_purify_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    collusion_api_collusion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollusionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similarity_api_similarity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_scan_api_import_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_library_api_demo_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    frame_api_frame_get: {
        parameters: {
            query: {
                path: string;
                t?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    thumb_api_thumb_get: {
        parameters: {
            query: {
                path: string;
                width?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_list_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    library_add_api_library_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_remove_api_library_delete: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_clear_api_library_all_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    media_api_media_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_video_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_video_api_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audio_analyze_api_audio_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desensitize_api_desensitize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesensitizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_videos_api_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outputs_api_outputs_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_output_api_outputs_delete: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outputs_counts_api_outputs_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    products_list_api_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    products_delete_api_products_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_ffmpeg_api_ffmpeg_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ffmpeg_install_status_api_ffmpeg_install_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    install_ffmpeg_api_ffmpeg_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_jobs_api_jobs_delete: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_job_api_jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_api_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_job_priority_api_jobs__job_id__priority_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    post_template_api_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_template_api_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variants_api_variants_get: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
