import type { components } from "@/lib/api-types";
import type { TemplateInfo } from "@/lib/backend";
import {
  SCHEMA_DEFAULT_TIER,
  TIER_DETAIL,
  TIER_DETAIL_SIGMA,
} from "@/lib/tiers";

/** 模板 payload：与后端 Pydantic TemplatePayload 契约一致，由 OpenAPI 生成。 */
export type TemplatePayload = components["schemas"]["TemplatePayload"];
export type Codec = TemplatePayload["codec"];

export const DEFAULT_TEMPLATE: TemplatePayload = {
  audioRemix: false,
  echoDefeat: false,
  antiReembed: false,
  rotate: 0,
  hashAttack: false,
  hashEpsilon: 0.08,
  hashMode: "phash",
  requant: 0,
  noise: 0,
  dctStep: 0,
  audioStrong: false,
  regradeOn: false,
  recropOn: false,
  temporalSub: 0,
  fftPhase: 0,
  dwtDetail: 0,
  hsvJitter: 0,
  jitter: 0,
  perspective: 0,
  warp: 0,
  facePerturb: 0,
  lpcAttack: 0,
  copyAttack: 0,
  nativeTemporal: true,
  qualityProtect: false,
  psnrTarget: 38,
  ssimTarget: 0.94,
  purifyStrength: 0,
  purifyDetail: TIER_DETAIL,
  purifyDetailSigma: TIER_DETAIL_SIGMA,
  purifyDetailWide: SCHEMA_DEFAULT_TIER.detail_wide,
  knownScheme: "",
  purifyTemporal: 0,
  purifyMaxEdge: SCHEMA_DEFAULT_TIER.max_edge,
  purifyBatch: SCHEMA_DEFAULT_TIER.batch,
  embeddingAttack: "",
  embeddingStrength: 0,
  embeddingVariant: "v2",
  embeddingAggressive: false,
  autoProfile: false,
  sharpness: false,
  colorRestore: false,
  denoise: false,
  spoof: false,
  codec: "H.264",
  lossless: false,
  resolution: "保持原始分辨率",
  bitrate: null,
  gop: null,
  fpsOut: null,
};

/** 读取模板参数；兼容旧版 restruct/audio 字段。 */
export function payloadOf(template: TemplateInfo): TemplatePayload {
  const raw = (template.payload ?? {}) as Record<string, unknown>;
  return {
    audioRemix: (raw.audioRemix as boolean) ?? (raw.audio as boolean) ?? true,
    echoDefeat: (raw.echoDefeat as boolean) ?? false,
    antiReembed: (raw.antiReembed as boolean) ?? false,
    rotate: (raw.rotate as number) ?? 0,
    hashAttack: (raw.hashAttack as boolean) ?? false,
    hashEpsilon: (raw.hashEpsilon as number) ?? 0.045,
    hashMode: (raw.hashMode as string) ?? "joint",
    requant: (raw.requant as number) ?? 0,
    noise: (raw.noise as number) ?? 0,
    dctStep: (raw.dctStep as number) ?? 0,
    audioStrong: (raw.audioStrong as boolean) ?? false,
    regradeOn: (raw.regradeOn as boolean) ?? true,
    recropOn: (raw.recropOn as boolean) ?? false,
    temporalSub: (raw.temporalSub as number) ?? 0,
    fftPhase: (raw.fftPhase as number) ?? 0,
    dwtDetail: (raw.dwtDetail as number) ?? 0,
    hsvJitter: (raw.hsvJitter as number) ?? 0,
    jitter: (raw.jitter as number) ?? 0,
    perspective: (raw.perspective as number) ?? 0,
    warp: (raw.warp as number) ?? 0,
    facePerturb: (raw.facePerturb as number) ?? 0,
    lpcAttack: (raw.lpcAttack as number) ?? 0,
    copyAttack: (raw.copyAttack as number) ?? 0,
    nativeTemporal: (raw.nativeTemporal as boolean) ?? false,
    qualityProtect: (raw.qualityProtect as boolean) ?? false,
    psnrTarget: (raw.psnrTarget as number) ?? 38,
    ssimTarget: (raw.ssimTarget as number) ?? 0.94,
    purifyStrength: (raw.purifyStrength as number) ?? 0,
    purifyDetail: (raw.purifyDetail as number) ?? TIER_DETAIL,
    purifyDetailSigma: (raw.purifyDetailSigma as number) ?? TIER_DETAIL_SIGMA,
    purifyDetailWide:
      (raw.purifyDetailWide as boolean) ?? SCHEMA_DEFAULT_TIER.detail_wide,
    knownScheme: (raw.knownScheme as TemplatePayload["knownScheme"]) ?? "",
    purifyTemporal: (raw.purifyTemporal as number) ?? 0,
    purifyMaxEdge: (raw.purifyMaxEdge as number) ?? SCHEMA_DEFAULT_TIER.max_edge,
    purifyBatch: (raw.purifyBatch as number) ?? SCHEMA_DEFAULT_TIER.batch,
    embeddingAttack: (raw.embeddingAttack as TemplatePayload["embeddingAttack"]) ?? "",
    embeddingStrength: (raw.embeddingStrength as number) ?? 0,
    embeddingVariant:
      (raw.embeddingVariant as TemplatePayload["embeddingVariant"]) ?? "v2",
    embeddingAggressive: (raw.embeddingAggressive as boolean) ?? false,
    autoProfile: (raw.autoProfile as boolean) ?? false,
    sharpness: (raw.sharpness as boolean) ?? true,
    colorRestore: (raw.colorRestore as boolean) ?? true,
    denoise: (raw.denoise as boolean) ?? true,
    spoof: (raw.spoof as boolean) ?? false,
    codec: (raw.codec as Codec) ?? "H.264",
    lossless: (raw.lossless as boolean) ?? false,
    resolution: (raw.resolution as string) ?? "保持原始分辨率",
    bitrate: (raw.bitrate as number) ?? null,
    gop: (raw.gop as number) ?? null,
    fpsOut: (raw.fpsOut as number) ?? null,
  };
}
